### ISSUE TITLE
Adding a configuration-driven interface

### ISSUE THREAD

**Issue by jscanvic** [deepinv/deepinv#496]
High-level deep learning libraries like `ultralytics` feature configuration-driven interfaces for training and fine-tuning neural networks on custom data. Instead of tweaking a fully-fledged training script, a third-party program is distributed with the library and it can be used along with configuration files to train pre-existing models on custom data. At the moment, the library only supports programmatic usage which can deter less technical users from using the library. I suggest we add support for this use case.

A practical use case might look like:

```bash
python -m deepinv train --config ./config.yaml
```

```yaml
# config.yaml
dataset: ./dataset.h5
loss: EILoss
epochs: 100
model: UNet
out_dir: ./weights
...
```

**How**

The implementation can be as simple as a basic CLI wrapper over the existing trainer.
